name: Auto Merge Main into All Branches

on:
  push:
    branches:
      - main

jobs:
  update-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "Jose Angel Alvarez Carranza"
          git config --global user.email "joseangelalvarezx@gmail.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Merge main into all branches
        run: |
          branches=$(git branch -r | grep -v "main" | sed 's/origin\///')
          for branch in $branches; do
            git checkout $branch
            git merge origin/main --no-edit --allow-unrelated-histories
            git push https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }} $branch
          done

